### ISSUE TITLE
Juvo hitting permissions errors - readers seeing errored out columns

### ISSUE THREAD

**Issue by erica-sigma** [sigmacomputing/intercom_issues#5] opened 2019-07-02 18:56 UTC
> I created two teams: a reader team and an author team. The worksheet works fine in the author team but has errored columns when seen from the reader team.
 > The above screenshots are from a Juvo Reader login to Sigma

![](https://downloads.intercomcdn.com/i/o/131024478/06bbd610f90edd322871c69f/Screen+Shot+2019-06-28+at+5.15.03+PM.png)

**Link:** [Conversation with Huang Pan](https://app.intercom.com/a/apps/gu1e0q0t/respond/inbox/all/conversations/22657981014)

**Customer:** [Huang Pan](https://app.intercom.com/a/apps/gu1e0q0t/users/5c7f23f220a4bf485020ea24/all-conversations) from [Juvo](https://app.intercom.com/a/apps/gu1e0q0t/companies/5d0bf432126bf11713574761)
**Customer ID:** 3ormTeGq1sThnAJfAy7KPoU5YEBAP
**Company ID:** ccb61e83-b6af-4e49-bbdf-8f607387a808
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/gu1e0q0t/respond/inbox/all/conversations/22657981014) when this issue is closed.

**Comment by jfranty** [comment] 2019-07-08 22:56
Duplicate of https://github.com/sigmacomputing/slate/issues/8399

**Closed by jfranty** 2019-07-08 22:56 UTC
